name: .NET

on:
  push:
    branches: [ main, proxy-fit ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Build
      shell: bash
      run: |
        pushd './src'
        dotnet build
        dotnet publish --configuration Release --output ./client-publish ./DurableDice.GameClient/DurableDice.GameClient.csproj
        dotnet publish --configuration Release --output ./function-publish ./DurableDice.Functions/DurableDice.Functions.csproj
        popd
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create -g DurableDice -f ./deploy/main.bicep -p functionAppKey=${{ secrets.FUNCTION_APP_KEY }}
    - name: Upload Static site
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -d '$web' --account-name durabledice -s ./src/client-publish/wwwroot
    - name: Publish Function App
      uses: Azure/functions-action@v1.3.1
      with:
        app-name: durabledice
        package: ./src/function-publish
      
