name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload Static site
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -d 'site' --account-name durabledice -s ./src/DurableDice/DurableDice.GameClient/publish/wwwroot
    - name: Publish Function App
      uses: Azure/functions-action@v1.3.1
      with:
        app-name: durabledice
        package: ./src/DurableDice/DurableDice.Functions/output
